# Autoscaler's deployment MUST be:
#   name: camunda-autoscaler
#   namespace: default
#   image: local.registry/camunda-autoscaler:1.0.0
#   imagePullPolicy: IfNotPresent

# otherwise the test framework won't find it and kind cluster won't be able to pull it

apiVersion: v1
kind: ServiceAccount
metadata:
  name: camunda-autoscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: camunda-autoscaler

rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camunda-autoscaler
  namespace: default
subjects:
- kind: ServiceAccount
  name: camunda-autoscaler
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: camunda-autoscaler # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io 


---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-autoscaler
  namespace: default
  labels:
    app: camunda-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-autoscaler
  template:
    metadata:
      labels:
        app: camunda-autoscaler
    spec:
      containers:
      - name: camunda-autoscaler
        image: local.registry/camunda-autoscaler:1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CAMUNDA_URL
            value: "http://camunda-service:8080/"
          - name: CAMUNDA_API
            value: "engine-rest/history/process-instance/count"
          - name: DELAY
            value: "10"
          - name: DEPLOY_NAME
            value: camunda-deployment
          - name: PROCESS_CYCLE
            value: "10"
          - name: PROCESS_MIN_PER_INSTANCE
            value: "20"
          - name: PROCESS_MAX_PER_INSTANCE
            value: "50"
          - name: POD_MAX_SCALE
            value: "4"
        resources:
          limits:
            cpu: 1
            memory: 256M
          requests:
            cpu: 1
            memory: 256M    
      serviceAccountName: camunda-autoscaler 
      terminationGracePeriodSeconds: 5
