# WARNING: You don't need to edit this file!
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:12.2-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: process-engine
        - name: POSTGRES_USER
          value: camunda
        - name: POSTGRES_PASSWORD
          value: camunda
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: psql-data
  volumeClaimTemplates:
  - metadata:
      name: psql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

